### ISSUE TITLE
Only support smart plugs, what about others ?

### ISSUE THREAD

**Issue by polyedre** [polyedre/tuya-lan#1]
This repo only support smart plug and is specific for retrieving monitored data about power consumption, how can I add support for other devices ?

**Comment by polyedre** [comment]
As this library rely on [python-tuya](https://github.com/clach04/python-tuya), the best is to try manually to get your device working.
1. Get your `local_key` and your `device_id`
2. Try to get status
```
>>> import pytuya
>>> device = pytuya.OutletDevice('DEVICE_ID_HERE', 'IP_ADDRESS_HERE', 'LOCAL_KEY_HERE')
>>> device.status()
```
3. Try to set status to understand how it works
When the feature you want is possible manually, you can add support by writing a `fan.py`, `switch.py`, etc module
I think you can take inspiration on `sensor.py` even if this is not the best piece of code

Other inspiration:
https://github.com/home-assistant/home-assistant/pull/11000/files
https://github.com/home-assistant/home-assistant/pull/15399/files

**Comment by RXM307** [comment]
Both of my devices are timing out locally, they work fine via the App 
(I've even put my phone in airport mode, as I've read many devices only allow 1 connection)

>>> import pytuya
>>> device = pytuya.OutletDevice('xxxxxxxxx', 'xxx.xx.xxx.xxx', 'xxxxxx')
>>> device.status()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/pytuya/__init__.py", line 256, in status
    data = self._send_receive(payload)
  File "/usr/local/lib/python3.7/site-packages/pytuya/__init__.py", line 166, in _send_receive
    data = s.recv(1024)
socket.timeout: timed out

**Comment by polyedre** [comment]
Yes, you need to close the app if you want to use this API :)

**Comment by RXM307** [comment]
Still cannot access, even with the App Closed or even without the mobile device on the wifi

**Comment by polyedre** [comment]
You can check if you receive broadcast from the device. When it is not in communication with a device, it sends UDP packets to port 6666 using broadcast.
Try `nc -lup 6666` (make sure the app is closed)

**Comment by RXM307** [comment]
Nope had this running while i was out of the house the other day and nothing.....

**Comment by RXM307** [comment]
Interestingly I now have my devices working locally with this custom component https://github.com/stast1/localtuya how this differs to yours I don't know as it is also using pytuya, so this issue can be closed unless you are going to add this support for yourself.

**Comment by polyedre** [comment]
Very strange, because the part that wasn't working for you seemed to be the pytuya part !
